/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas.Usuarios;

import Models.Usuario;
import Services.UsuarioService;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author diego
 */



public class UsuarioAgregar extends JDialog {

    /**
     * Creates new form UsuarioAgregar
     */
    
    private JTextField txtNombre, txtContraseña;
    private JComboBox<String> cmbRol;
    private JButton btnGuardar, btnCancelar;
    private UsuarioService usuarioService;
    private Usuario usuario;
    
    
    public UsuarioAgregar() {
        initComponents();
        
        
    }
    
    public UsuarioAgregar(JFrame parent, Usuario usuario) {
        super(parent, true);
        this.usuario = usuario;
        usuarioService = new UsuarioService();

        setTitle(usuario == null ? "Agregar Usuario" : "Editar Usuario");
        setSize(400, 300);
        setLocationRelativeTo(parent);

        // Campos
        txtNombre = new JTextField(20);
        txtContraseña = new JPasswordField(20);
        cmbRol = new JComboBox<>(new String[]{"Contador", "Auxiliar", "Gerente", "Administrador"});

        btnGuardar = new JButton("Guardar");
        btnCancelar = new JButton("Cancelar");

        // Si estamos editando, llenamos los campos con los datos del usuario
        if (usuario != null) {
            txtNombre.setText(usuario.getNombre());
            txtContraseña.setText(usuario.getContraseña());
            cmbRol.setSelectedItem(usuario.getRol());
        }

        btnGuardar.addActionListener(e -> guardarUsuario());
        btnCancelar.addActionListener(e -> dispose());

        JPanel panel = new JPanel(new GridLayout(4, 2));
        panel.add(new JLabel("Nombre:"));
        panel.add(txtNombre);
        panel.add(new JLabel("Contraseña:"));
        panel.add(txtContraseña);
        panel.add(new JLabel("Rol:"));
        panel.add(cmbRol);
        panel.add(btnGuardar);
        panel.add(btnCancelar);

        add(panel);
        
        }
        // Método para guardar el usuario
      private void guardarUsuario() {
        String nombre = txtNombre.getText();
        String contraseña = txtContraseña.getText();
        String rol = (String) cmbRol.getSelectedItem();

        if (usuario == null) {
            // Agregar nuevo usuario
            usuarioService.crearUsuario(new Usuario(nombre, contraseña, rol));
        } else {
            // Editar usuario existente
            usuario.setNombre(nombre);
            usuario.setContraseña(contraseña);
            usuario.setRol(rol);
            usuarioService.actualizarUsuario(usuario);
        }

        ((UsuarioPrincipal) getParent()).refrescarTabla();
        dispose();
    }
    
    
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuarioAgregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
